# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** [Input Nama]
- **Email:** [Input Email]
- **ID Dicoding:** [Input Username]

## Menentukan Pertanyaan Bisnis

**SMART Question** adalah sebuah framework untuk merumuskan pertanyaan secara terstruktur agar memeperoleh informasi yang mendalam.

* **Spesific (Spesifik)**
  * Pertanyaan harus jelas, fokus pada sebuah topik tertentu, dan tidak bermakna ganda. Hindari pertanyaan yang terlalu luas.
    * Salah: Bagaimana cara meningkatkan penjualan?
    * Benar: Faktor apa saja yang memengaruhi penurunan penjualan produk kategori elektronik di wilayah Jakarta selama kuartal terakhir?
* **Measurable (Terukur)**
  * Pertanyaan harus bisa dijawab dengan angka atau matrix yang konkret, harus tahu apa yang akan dihitung.
    * Salah: Apakah pelanggan senang dengan layanan kita?
    * Benar: Berapa skor rata-rata Customer Satisfaction untuk layanan purna jual bulan ini dibandingkan bulan lalu?
* **Action-Oriented (Berorientasi Aksi)**
  * Hasil dari pertanyaan harus bisa memberikan arahan untuk melakukan tindakan nyata. Jika pertanyaan terjawab, stakeholder harus tahu apa langkah selanjutnya.
    * Salah: Mengapa orang suka berbelanja?
    * Benar: Fitur apa pada aplikasi yang paling sering digunakan sebelum pengguna memutuskan untuk melakukan checkout?
* **Relevant (Relevan)**
  * Hasil dari pertanyaan harus sejalan dengan tujuan utama bisnis atau masalah yang sedang dihadapi.
    * Salah: Menanyakan tentang stok gudang saat masalah utamanya adalah efektivitas kampanye media sosial.
    * Benar: Apakah kampanye iklan di Instagram memberikan Return on Ad Spend (ROAS) yang lebih tinggi dibandingkan iklan di TikTok?
* **Time-bound (Terikat Waktu)**
  * Pertanyaan harus ada batasan waktu yang jelas agar analisis memiliki konteks yang tepat.
    * Salah: Berapa banyak pengguna baru kita?
    * Benar: Berapa tingkat pertumbuhan pengguna baru secara bulanan (Month-over-Month) sepanjang tahun 2025?

**Contoh pertanyaan bisnis yang memenuhi seluruh elemen SMART**

***"Faktor apa saja yang memengaruhi penurunan conversion rate pada pengguna aplikasi Android di wilayah Jabodetabek sebesar 5% selama periode Flash Sale Maret 2026?"***

Keterangan:

- **Specific**: Fokus pada "penurunan conversion rate" untuk "aplikasi Android" di "Jabodetabek". Bukan sekadar penjualan turun.
- **Measurable**: Ada angka konkret yang ingin dianalisis, yaitu penurunan sebesar "5%".
- **Action-Oriented**: Dengan mengetahui faktor penyebabnya misalnya bug pada versi Android tertentu atau kendala logistik di Jabodetabek, tim bisa langsung melakukan perbaikan teknis atau operasional.
- **Relevant**: Penurunan konversi saat Flash Sale adalah masalah kritis bagi bisnis retail/e-commerce.
- **Time-bound**: Dibatasi pada periode spesifik "Flash Sale Maret 2026".

- **Pertanyaan 1:** xxx
- **Pertanyaan 2:** xxx
- ...

## Import Semua Packages/Library yang Digunakan

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import os

## Data Wrangling

### Gathering Data

#### Load df ...

In [2]:
# 1. Baca sumber datanya
df = pd.read_csv('../answer_quality_dataset_dirty.csv')

print(f"Total Data: {df.shape[0]} Baris")
df.head()

Total Data: 5239 Baris

,sample_id,domain,role_family,target_role,competency,question,answer,role_relevance,star_structure,evidence_specificity,...,clarification_type,final_score_0_100,final_score_0_1,quality_label,has_tool,has_metric,has_impact,has_action,has_context,answer_length_words
0,AQD-03716F,Information & Technology,Data & AI,ML Engineer,Automated MLOps Pipelines,Pernahkah kamu terlibat dalam merancang pipeli...,"Iya, saya pernah terlibat dalam perancangan pi...",70.0,65.0,50.0,...,metric,62.25,0.6225,Average,1,0,0,1,1,130
1,AQD-FA7056,Information & Technology,Data & AI,ML Engineer,Career Motivation & Fit,"Kalau kamu diterima di posisi ML Engineer ini,...",Target utama saya dalam satu sampai dua tahun ...,95.0,90.0,95.0,...,none,92.55,0.9255,Strong,1,1,1,1,1,119
2,AQD-433BB3,Information & Technology,Data & AI,AI Engineer,Career Motivation & Fit,Dari semua project atau materi yang pernah kam...,Saya rasa titik balik yang paling signifikan b...,70.0,60.0,74.0,...,impact,67.30,0.6730,Average,1,0,0,1,1,152
3,AQD-B7FDA1,Information & Technology,Data & AI,AI Engineer,Deep Learning Architecture Design,Saat proses pelatihan (training) model deep le...,"Eh, anu... kalau soal itu ya, emm, sebenernya ...",40.0,20.0,20.0,...,context,28.00,0.2800,Weak,0,0,0,0,0,105
4,AQD-95CDCC,Information & Technology,Software Tester,QA Automation Engineer,Programmatic Integration Validation,Misalkan skrip otomatisasi API kamu berjalan s...,"Em, jadi kalau buat kasus itu, biasanya saya p...",70.0,60.0,50.0,...,technical,61.25,0.6125,Average,1,0,0,1,1,113

**Insight:** (Opsional)
- xxx
- xxx

### Assessing Data

#### Identifying ... problem

In [3]:
# 1. Mengecek informasi dasar dan tipe data
print("--- Informasi Data ---")
df.info()

--- Informasi Data ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5239 entries, 0 to 5238
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sample_id              5239 non-null   object
 1   domain                 5239 non-null   object
 2   role_family            5239 non-null   object
 3   target_role            5239 non-null   object
 4   competency             5239 non-null   object
 5   question               5239 non-null   object
 6   answer                 5228 non-null   object
 7   role_relevance         5237 non-null   float64
 8   star_structure         5226 non-null   float64
 9   evidence_specificity   5237 non-null   float64
 10  technical_accuracy     5237 non-null   float64
 11  communication_clarity  5236 non-null   float64
 12  self_awareness         5237 non-null   float64
 13  evidence_level         5239 non-null   int64
 14  weakness_tags          3492 non-null   object
 15  need_clarification     5239 non-null   bool
 16  clarification_type     5239 non-null   object
 17  final_score_0_100      5239 non-null   float64
 18  final_score_0_1        5239 non-null   float64
 19  quality_label          5233 non-null   object
 20  has_tool               5239 non-null   int64
 21  has_metric             5239 non-null   int64
 22  has_impact             5239 non-null   int64
 23  has_action             5239 non-null   int64
 24  has_context            5239 non-null   int64
 25  answer_length_words    5239 non-null   int64
dtypes: bool(1), float64(8), int64(7), object(10)
memory usage: 1.0+ MB

In [4]:
# 2. Mengecek missing values 
print("\n--- Jumlah Missing Values ---")
missing_values = df.isna().sum()
print(missing_values)

--- Jumlah Missing Values ---
sample_id                   0
domain                      0
role_family                 0
target_role                 0
competency                  0
question                    0
answer                     11
role_relevance              2
star_structure             13
evidence_specificity        2
technical_accuracy          2
communication_clarity       3
self_awareness              2
evidence_level              0
weakness_tags            1747
need_clarification          0
clarification_type          0
final_score_0_100           0
final_score_0_1             0
quality_label               6
has_tool                    0
has_metric                  0
has_impact                  0
has_action                  0
has_context                 0
answer_length_words         0
dtype: int64

In [5]:
# 3. Mengecek duplikasi
print("\n--- Jumlah Duplikasi ---")
print(df.duplicated().sum())

--- Jumlah Duplikasi ---
47

In [6]:
# 4. Statistik deskriptif
print("\n--- Statistik Deskriptif ---")
display(df.describe())

--- Statistik Deskriptif ---

,role_relevance,star_structure,evidence_specificity,technical_accuracy,communication_clarity,self_awareness,evidence_level,final_score_0_100,final_score_0_1,has_tool,has_metric,has_impact,has_action,has_context,answer_length_words
count,5237.000000,5226.000000,5237.000000,5237.000000,5236.000000,5237.000000,5239.000000,5239.000000,5239.000000,5239.000000,5239.000000,5239.000000,5239.000000,5239.000000,5239.000000
mean,67.070078,57.537887,56.702501,62.846095,66.448434,57.160397,3.013934,61.354524,0.613545,0.631609,0.322772,0.370109,0.709868,0.824203,130.162626
std,24.327845,31.408282,30.282117,27.357555,26.106991,26.398845,1.626315,27.256288,0.272563,0.482414,0.467581,0.482880,0.453866,0.380684,48.203153
min,20.000000,0.000000,0.000000,0.000000,10.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99.000000
25%,40.000000,20.000000,20.000000,30.000000,40.000000,30.000000,1.000000,30.250000,0.302500,0.000000,0.000000,0.000000,0.000000,1.000000,101.000000
50%,70.000000,60.000000,55.000000,65.000000,75.000000,50.000000,3.000000,62.750000,0.627500,1.000000,0.000000,0.000000,1.000000,1.000000,124.000000
75%,95.000000,90.000000,90.000000,90.000000,95.000000,85.000000,5.000000,92.750000,0.927500,1.000000,1.000000,1.000000,1.000000,1.000000,149.000000
max,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,5.000000,98.000000,0.980000,1.000000,1.000000,1.000000,1.000000,1.000000,492.000000

In [7]:
# cek nilai unik untuk kolom kategorikal
print("\n--- Nilai Unik untuk Kolom Kategorikal ---")  
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    unique_values = df[col].unique()
    print(f"{col}: {len(unique_values)} nilai unik")
    print(f"Contoh nilai unik: {unique_values[:5]}\n")

--- Nilai Unik untuk Kolom Kategorikal ---
sample_id: 5189 nilai unik
Contoh nilai unik: ['AQD-03716F' 'AQD-FA7056' 'AQD-433BB3' 'AQD-B7FDA1' 'AQD-95CDCC']

domain: 1 nilai unik
Contoh nilai unik: ['Information & Technology']

role_family: 5 nilai unik
Contoh nilai unik: ['Data & AI' 'Software Tester' 'Web Development' 'Mobile Development'
 'Infrastructure, Cloud & Security']

target_role: 16 nilai unik
Contoh nilai unik: ['ML Engineer' 'AI Engineer' 'QA Automation Engineer' 'Data Analyst'
 'Frontend Developer']

competency: 58 nilai unik
Contoh nilai unik: ['Automated MLOps Pipelines' 'Career Motivation & Fit'
 'Deep Learning Architecture Design' 'Programmatic Integration Validation'
 'Advanced Component Lifecycles & State']

question: 200 nilai unik
Contoh nilai unik: ['Pernahkah kamu terlibat dalam merancang pipeline otomatisasi untuk retraining model secara end-to-end? Boleh ceritakan bagaimana kamu menyusun alurnya, mulai dari pemrosesan fitur secara otomatis hingga pengujian performanya?'
 'Kalau kamu diterima di posisi ML Engineer ini, apa target atau harapan terbesarmu dalam 1 sampai 2 tahun ke depan?'
 "Dari semua project atau materi yang pernah kamu pelajari, bagian mana sih yang bikin kamu merasa paling 'klik' dan yakin berkarir di jalur ini?"
 'Saat proses pelatihan (training) model deep learning, terkadang kita menemui masalah di mana model sulit mencapai konvergensi atau nilai loss-nya stagnan. Pendekatan teknis seperti apa yang biasanya kamu lakukan untuk menstabilkan proses pelatihan tersebut?'
 'Misalkan skrip otomatisasi API kamu berjalan setiap malam, lalu mendeteksi kegagalan (failure) yang fatal pada sistem. Bagaimana cara kamu mengotomatisasi agar notifikasi atau laporan error tersebut bisa langsung dikirim ke tim developer secara real-time?']

answer: 5179 nilai unik
Contoh nilai unik: ['Iya, saya pernah terlibat dalam perancangan pipeline otomatisasi untuk retraining model di proyek sebelumnya. Jadi tuh, alurnya pertama-tama kita pakai Airflow sebagai orchestrator-nya. Jadi setiap ada data baru yang masuk ke data lake, sistem otomatis akan memicu pipeline buat pemrosesan fitur. Kita pakai script Python biasa untuk feature engineering-nya, kemudian datanya disimpan ke database. Nah, setelah fitur siap, pipeline akan menjalankan proses retraining model menggunakan model yang sudah ada sebelumnya sebagai base. Terus, untuk tahap pengujiannya, kita biasanya ngecek output prediksi model di lingkungan staging sebelum di-deploy ke produksi. Jadi intinya kalau hasil prediksinya nggak terlalu melenceng, ya modelnya kita push ke server produksi lewat CI/CD pipeline supaya bisa langsung digunakan oleh aplikasi. Ya kurang lebih alurnya seperti itu sih, cukup standar untuk menjaga model tetap up-to-date dengan data terbaru.'
 'Target utama saya dalam satu sampai dua tahun ke depan adalah membawa dampak langsung pada skalabilitas sistem ML di perusahaan ini. Misalnya, saat ini saya melihat ada potensi untuk mengoptimalkan pipeline retraining model. Berkaca dari pengalaman saya sebelumnya, saya berhasil membangun sistem otomatisasi data pipeline menggunakan Airflow dan DVC yang mampu memangkas waktu retraining model dari tiga hari menjadi hanya empat jam. Jadi, ekspektasi saya di sini, saya ingin menerapkan optimasi serupa untuk mengurangi latensi inferensi model sebesar 30% dan meningkatkan akurasi prediksi melalui implementasi MLOps yang lebih robust. Saya ingin memastikan bahwa model yang kita deploy tidak hanya akurat secara teknis, tapi benar-benar menjadi aset bisnis yang performanya terukur setiap bulannya melalui dashboard monitoring yang saya kembangkan nanti.'
 "Saya rasa titik balik yang paling signifikan bagi saya adalah saat mengerjakan project implementasi sistem pengenalan entitas untuk data teks tidak terstruktur di perusahaan sebelumnya. Saat itu, saya mendalami arsitektur Transformer dan mencoba melakukan fine-tuning pada model BERT menggunakan dataset internal yang cukup besar. Saya menghabiskan waktu berminggu-minggu untuk melakukan pembersihan data secara manual, melakukan eksperimen pada hyperparameter, dan menyusun pipeline preprocessing agar model bisa mengenali terminologi spesifik industri kami dengan lebih presisi. Saya benar-benar tenggelam dalam teknis pembersihan dataset, memperbaiki ketidakseimbangan kelas pada label, serta bereksperimen dengan berbagai library pemrosesan bahasa alami yang tersedia. Proses mengutak-atik arsitektur model dan memastikan alur kerja data berjalan dengan lancar tanpa ada error di tahap preprocessing benar-benar membuat saya merasa sangat antusias. Saya merasa sangat 'klik' ketika melihat bagaimana baris demi baris kode yang saya tulis mulai mampu memproses data dengan pola yang jauh lebih kompleks dibandingkan metode berbasis aturan tradisional yang kami gunakan sebelumnya."
 'Eh, anu... kalau soal itu ya, emm, sebenernya saya sering sih ngalamin hal kayak gitu pas lagi training. Biasanya ya, emm, model saya itu kayak loss-nya stuck gitu kan, ehh, terus ya saya coba-coba aja sih ganti learning rate-nya, mungkin dikecilin atau gimana ya, emm, saya juga kadang ganti batch size-nya biar lebih stabil. Ya, gitu sih, emm, soalnya kadang kalau datanya kurang oke atau arsitekturnya kayaknya terlalu kompleks, ya modelnya jadi susah belajar ya. Terus apa lagi ya, hmm, ya intinya sih kita coba-coba tuning aja sih parameter-parameternya sampai nanti loss-nya turun sendiri. Gitu sih biasanya yang saya lakukan kalau lagi ngerjain project AI.'
 'Em, jadi kalau buat kasus itu, biasanya saya pakai integrasi webhook sih ya. Jadi tuh, pas skrip API testing saya jalan malam-malam, terus ada gagal atau error fatal, nah itu sistemnya bakal otomatis nge-trigger HTTP request ke Slack atau aplikasi chat yang kita pakai di tim. Saya biasanya pasang logic-nya di bagian akhir skrip, jadi kalau status code-nya bukan 200, dia langsung kirim payload berisi pesan error-nya gitu. Eh, terus ya mungkin ditambahin juga sih link ke dashboard biar tim developer bisa langsung ngecek log-nya. Sejauh ini sih cara itu yang paling umum saya gunain biar tim bisa dapet update langsung pas pagi-pagi, jadi pas masuk kantor mereka udah tahu ada yang bermasalah.']

weakness_tags: 789 nilai unik
Contoh nilai unik: ['measurable_result_missing;impact_missing;technical_detail_missing' nan
 'impact_missing;measurable_result_missing;star_structure_missing'
 'context_missing;contribution_unclear;star_structure_missing;technical_detail_missing;communication_unclear'
 'technical_detail_missing;measurable_result_missing;impact_missing']

clarification_type: 13 nilai unik
Contoh nilai unik: ['metric' 'none' 'impact' 'context' 'technical']

quality_label: 7 nilai unik
Contoh nilai unik: ['Average' 'Strong' 'Weak' 'STRONG' 'average']

**Steps to Take:**
- xxx
- xxx

**Insight:** (Opsional)
- xxx
- xxx

### Cleaning Data

#### Fixing Duplicate Data, Missing Value, Format Standarization, Outlier problem

In [8]:
print("=== Proses Data Cleaning ===")
df_clean = df.copy()

# 1. Menangani Data Duplikat
df_clean = df_clean.drop_duplicates()
print(f"[-] Data duplikat berhasil dihapus. Sisa baris: {df_clean.shape[0]}")

# 2. Menangani Missing Values (System Error)
# Hapus baris yang kolom-kolom pentingnya bolong/kosong
kolom_kritikal = ['answer', 'quality_label', 'star_structure', 'role_relevance', 'communication_clarity', 'technical_accuracy', 'evidence_specificity', 'self_awareness']
df_clean = df_clean.dropna(subset=kolom_kritikal)
print(f"[-] Missing values karena system error berhasil didrop. Sisa baris: {df_clean.shape[0]}")

# 3. Menangani Missing Values (Business Logic)
# Kolom weakness_tags yang kosong kita isi dengan label 'None' (artinya tidak ada kelemahan)
df_clean['weakness_tags'] = df_clean['weakness_tags'].fillna('None')
print("[-] Missing values pada 'weakness_tags' berhasil diisi dengan 'None'.")

# 4. Standardisasi Teks (Mengatasi Inconsistent Format pada Label)
df_clean['quality_label'] = df_clean['quality_label'].astype(str).str.strip().str.title()
print("[-] Format penulisan quality_label diseragamkan (Weak, Average, Strong).")

# 5. Mengatasi Outlier / Anomali Angka
# Cek dulu ada berapa baris yang kena anomali -99
total_anomali = (df_clean['answer_length_words'] == -99).sum()
print(f"\n[!] Menemukan {total_anomali} baris dengan panjang kata -99.")

# Jalankan fungsi hitung ulang kata hanya untuk baris yang nilainya -99
# .split() akan memecah teks berdasarkan spasi, lalu len() menghitung total katanya
df_clean.loc[df_clean['answer_length_words'] == -99, 'answer_length_words'] = \
    df_clean[df_clean['answer_length_words'] == -99]['answer'].apply(lambda x: len(str(x).split()))

print("[-] Nilai anomali -99 berhasil diperbaiki dengan metode kalkulasi ulang!")
print(f" Sisa baris final (aman tidak ada yang terbuang): {df_clean.shape[0]}")

print("\n=== Proses Cleaning Selesai! Data siap digunakan ===")

=== Proses Data Cleaning ===
[-] Data duplikat berhasil dihapus. Sisa baris: 5192
[-] Missing values karena system error berhasil didrop. Sisa baris: 5162
[-] Missing values pada 'weakness_tags' berhasil diisi dengan 'None'.
[-] Format penulisan quality_label diseragamkan (Weak, Average, Strong).

[!] Menemukan 6 baris dengan panjang kata -99.
[-] Nilai anomali -99 berhasil diperbaiki dengan metode kalkulasi ulang!
 Sisa baris final (aman tidak ada yang terbuang): 5162

=== Proses Cleaning Selesai! Data siap digunakan ===

**Insight:** (Opsional)
- xxx
- xxx

**Insight:** (Opsional)
- xxx
- xxx

## Exploratory Data Analysis (EDA)

### Explore ...

In [ ]:
# 5. Visualisasi distribusi target variable
plt.figure(figsize=(6, 4))
sns.countplot(x='quality_label', data=df)
plt.title('Distribusi Kualitas Jawaban')
plt.xlabel('Kualitas Jawaban')
plt.ylabel('Jumlah')
plt.show()
# 6. Visualisasi distribusi fitur numerik
numerical_cols = df.select_dtypes(include=[np.number]).columns
for col in numerical_cols:
    plt.figure(figsize=(6, 4))
    sns.histplot(df[col], kde=True)
    plt.title(f'Distribusi {col}')
    plt.xlabel(col)
    plt.ylabel('Frekuensi')
    plt.show()
# 7. Visualisasi hubungan antara fitur numerik dan target variable
for col in numerical_cols:
    plt.figure(figsize=(6, 4))
    sns.boxplot(x='quality_label', y=col, data=df)
    plt.title(f'{col} vs Kualitas Jawaban')
    plt.xlabel('Kualitas Jawaban')
    plt.ylabel(col)
    plt.show()
# 8. Visualisasi hubungan antara fitur kategorikal dan target variable
for col in categorical_cols:
    plt.figure(figsize=(6, 4))
    sns.countplot(x=col, hue='quality_label', data=df)
    plt.title(f'{col} vs Kualitas Jawaban')
    plt.xlabel(col)
    plt.ylabel('Jumlah')
    plt.legend(title='Kualitas Jawaban')
    plt.xticks(rotation=45)
    plt.show()

## Visualization & Explanatory Analysis

### Pertanyaan 1:

### Pertanyaan 2:

**Insight:** (Opsional)
- xxx
- xxx

## Analisis Lanjutan (Opsional)

**Insight:** (Opsional)
- xxx
- xxx

## Conclusion & Recommendation

- **Conclusion pertanyaan 1:** xxx
- **Conclusion pertanyaan 2:** xxx
- ...

**Rekomendasi Action Item:**
- xxx
- xxx